---
# vars file for cyhy_mailer

# reporter mongo username
reporter_user: "{{ lookup('aws_ssm', '/cyhy/mongo/users/reporter/user') }}"
# reporter mongo password
reporter_pw: "{{ lookup('aws_ssm', '/cyhy/mongo/users/reporter/password') }}"
# reporter mongo database
reporter_db: "{{ lookup('aws_ssm', '/cyhy/mongo/users/reporter/database') }}"
