blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Questions & Help
    url: https://github.com/cisagov/.github/blob/develop/QUESTIONS.md
    about: If you have questions, visit GitHub Discussions and Wiki pages
