---
galaxy_info:
  author: VM Fusion Dev
  company: CISA Cyber Assessments
  description: Configure MongoDB with our desired users and settings
  galaxy_tags: []
  license: CC0
  # Our standalone Ansible roles require this Ansible version
  min_ansible_version: "2.10"
  namespace: cyhy
  platforms:
    - name: Debian
      versions:
        - stretch
        - buster
  role_name: mongo

dependencies: []
