---
# tasks file for orchestrator
- name: Create the /var/cyhy/orchestrator directory
  file:
    path: /var/cyhy/orchestrator
    state: directory
    mode: 0755

- name: Download and untar the orchestrator tarball
  unarchive:
    src: https://api.github.com/repos/cisagov/orchestrator/tarball/develop
    dest: /var/cyhy/orchestrator
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

- name: Create the mount point for the reports volume
  file:
    path: /var/cyhy/orchestrator/output
    state: directory
