---
# tasks file for upgrade
- name: Install aptitude
  apt:
    name: 'aptitude'
    state: latest
    update_cache: yes
    force_apt_get: yes
  when: ansible_os_family == "Debian"

- name: Upgrade all packages
  package:
    name: '*'
    state: latest
    update_cache: yes

