---
galaxy_info:
  author: VM Fusion Dev
  company: CISA Cyber Assessments
  description: Set up the requirements for the cisagov/code-gov-update Docker image
  galaxy_tags: []
  license: CC0
  # Our standalone Ansible roles require this Ansible version
  min_ansible_version: "2.10"
  namespace: cyhy
  platforms:
    - name: Debian
      versions:
        - stretch
        - buster
        - bullseye
  role_name: code_gov_update

dependencies: []
