---
# vars file for orchestrator

# reporter mongo username
reporter_user: "{{ lookup('aws_ssm', '/cyhy/mongo/users/reporter/user') }}"
# reporter mongo password
reporter_pw: "{{ lookup('aws_ssm', '/cyhy/mongo/users/reporter/password') }}"
# reporter mongo database
reporter_db: "{{ lookup('aws_ssm', '/cyhy/mongo/users/reporterXS/database') }}"

# scan-reader mongo username
scan_reader_user: "{{ lookup('aws_ssm', '/cyhy/mongo/users/scan-reader/user') }}"
# scan-reader mongo password
scan_reader_pw: "{{ lookup('aws_ssm', '/cyhy/mongo/users/scan-reader/password') }}"
# scan-reader mongo database
scan_reader_db: "{{ lookup('aws_ssm', '/cyhy/mongo/users/scan-reader/database') }}"

# scan-writer mongo username
scan_writer_user: "{{ lookup('aws_ssm', '/cyhy/mongo/users/scan-writer/user') }}"
# scan-writer mongo password
scan_writer_pw: "{{ lookup('aws_ssm', '/cyhy/mongo/users/scan-writer/password') }}"
# scan-writer mongo database
scan_writer_db: "{{ lookup('aws_ssm', '/cyhy/mongo/users/scan-writer/database') }}"
